site_name: Granite WMS
site_url: https://granitewms.github.io/granitedocs/
nav: 
  - Home: index.md
  - Manuals:
    - Custodian API: custodian-api/manual.md
    - Integration:
      - Accpac: 
        - integration/accpac/index.md
        - SDK Provider: integration/accpac/sdk-provider.md
        - Integration Jobs: integration/accpac/integration-jobs.md
      - Evolution: 
        - integration/evo/index.md
        - SDK Provider: integration/evo/sdk-provider.md
        - Integration Jobs: integration/evo/integration-jobs.md
      - Omni: integration/omni/sdk-provider.md
      - QuickBooks: integration/quickbooks/native-app.md
      - SAPB1: integration/sapb1/sdk-provider.md
      - Syspro: integration/syspro/sdk-provider.md
    - Label Printing: 
      - Bartender: label-printing/bartender/manual.md
      - ZPL: label-printing/zpl/manual.md
    - Repository API: repository-api/manual.md
    - Scheduler: scheduler/manual.md
    - SQLCLR: 
      - sqlclr/index.md
      - Getting Started: sqlclr/getting-started.md
      - CLR Procedure Reference: sqlclr/reference.md
    - Utility API:
      - utility-api/index.md
      - Getting Started: utility-api/getting-started.md
      - Email Service: utility-api/email-service.md
      - Reporting Service: utility-api/reporting-service.md
      - SQL Export Service: utility-api/sql-export-service.md
    - Web Desktop: webdesktop/manual.md
    - SSRS: SSRS/getting-started.md
  - Release Notes:
    - Database: database/release-notes.md 
    - Label Printing:
      - ZPL: label-printing/zpl/release-notes.md
    - Scheduler: scheduler/release-notes.md
    - SQLCLR: sqlclr/release-notes.md
    - Utility API: utility-api/release-notes.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html