site_name: Granite WMS Documentation
site_url: https://granitewms.github.io/GraniteDocs/
extra_css:
  - extra_css/custom.css
extra_javascript:
  - extra_js/custom.js
nav: 
  - Home: index.md
  - Documentation:
    - Scaffold: scaffold/manual.md
    - Label Printing: 
      - Bartender: label-printing/bartender/manual.md
      - ZPL: label-printing/zpl/manual.md
    - Integration:
      - Accpac: 
        - integration/accpac/index.md
        - SDK Provider: integration/accpac/sdk-provider.md
        - Integration Jobs: integration/accpac/integration-jobs.md
      - Acumatica:
        - integration/acumatica/index.md
        - Acumatica Overview: integration/acumatica/acumatica-overview.md
        - SDK Provider: integration/acumatica/sdk-provider.md
        - Integration Jobs: integration/acumatica/integration-jobs.md
      - CIN7:
        - integration/cin7/index.md
        - CIN7 Overview: integration/cin7/cin7-overview.md
        - SDK Provider: integration/cin7/sdk-provider.md
        - Integration Jobs: integration/cin7/integration-jobs.md
      - Evolution: 
        - integration/evo/index.md
        - SDK Provider: integration/evo/sdk-provider.md
        - Integration Jobs: integration/evo/integration-jobs.md
      - ISync:
        - integration/isync/index.md
        - SDK Provider: integration/isync/sdk-provider.md
        - Integration Jobs: integration/isync/integration-jobs.md
      - Omni: integration/omni/sdk-provider.md
      - QuickBooks: integration/quickbooks/native-app.md
      - SAPB1: integration/sapb1/sdk-provider.md
      - Syspro: integration/syspro/sdk-provider.md
      - Sage 100: 
        - integration/sage100/index.md
        - SDK Provider: integration/sage100/sdk-provider.md
        - Integration Jobs: integration/sage100/integration-jobs.md
      - Sage Intacct: 
        - integration/intacct/index.md
        - SDK Provider: integration/intacct/sdk-provider.md
        - Integration Jobs: integration/intacct/integration-jobs.md
    - Web Desktop: 
      - webdesktop/index.md
      - Data Grid: webdesktop/datagrid/datagrid.md
      - Data Capture: webdesktop/datacapture/data-capture.md
    - Scanner Application: android-application/manual.md
    - Business API: business-api/manual.md
    - Custodian API: 
      - custodian-api/index.md
      - Getting Started: custodian-api/getting-started.md
      - Process Template Service: custodian-api/process-template-service.md
      - Email Service: custodian-api/email-service.md
      - Reporting Service: custodian-api/reporting-service.md
      - SQL Export Service: custodian-api/sql-export-service.md
      - Scheduler: scheduler/manual.md    
    - Customization:
      - customization/index.md
      - SQLCLR: 
        - sqlclr/index.md
        - Getting Started: sqlclr/getting-started.md
        - Version 6 Upgrade Guide: sqlclr/version-6-upgrade-guide.md
        - CLR Procedure Reference: sqlclr/reference.md
    - Application Security: 
      - security/index.md
      - System Security: security/system-security.md
      - Permissions: security/user-permissions.md
      - API Keys: security/api-keys.md      
  - Tools & Technology:
    - tools/index.md
    - IIS: iis/getting-started.md
    - SSRS: ssrs/getting-started.md  
    - Jam.dev: tools/jam.md
    - Jaeger: tools/jaeger.md
    - Apache NiFi: tools/nifi.md
  - Release Notes:
    - updates/index.md
    - What's New:
      - V4: updates/V4/whats-new.md
      - V5: 
        - Whats New : updates/V5/whats-new.md
        - Product Update: updates/V5/product-update.md
      - V6: 
        - Whats New : updates/V6/whats-new.md
        - CheatSheet : updates/V6/cheatsheet.md
    - Hotfixes: updates/release-notes.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
extra:
  version:
    provider: mike