site_name: Granite WMS
site_url: https://granitewms.github.io/granitedocs/
extra_css:
  - extra_css/custom.css
nav: 
  - Home: index.md
  - Manuals:
    - Scaffold: scaffold/manual.md
    - IIS: iis/getting-started.md
    - SSRS: ssrs/getting-started.md
    - API:
      - Repository API: repository-api/manual.md
      - Custodian API: 
        - Manual: custodian-api/manual.md
        - Best Practice: custodian-api/best-practice.md
      - Business API: business-api/manual.md  
      - Utility API:
        - utility-api/index.md
        - Getting Started: utility-api/getting-started.md
        - Email Service: utility-api/email-service.md
        - Reporting Service: utility-api/reporting-service.md
        - SQL Export Service: utility-api/sql-export-service.md
    - Label Printing: 
      - Bartender: label-printing/bartender/manual.md
      - ZPL: label-printing/zpl/manual.md
    - Integration:
      - Accpac: 
        - integration/accpac/index.md
        - SDK Provider: integration/accpac/sdk-provider.md
        - Integration Jobs: integration/accpac/integration-jobs.md
      - Acumatica:
        - integration/acumatica/index.md
        - Acumatica Overview: integration/acumatica/acumatica-overview.md
        - SDK Provider: integration/acumatica/sdk-provider.md
        - Integration Jobs: integration/acumatica/integration-jobs.md
      - Evolution: 
        - integration/evo/index.md
        - SDK Provider: integration/evo/sdk-provider.md
        - Integration Jobs: integration/evo/integration-jobs.md
      - Omni: integration/omni/sdk-provider.md
      - QuickBooks: integration/quickbooks/native-app.md
      - SAPB1: integration/sapb1/sdk-provider.md
      - Syspro: integration/syspro/sdk-provider.md
      - Sage 100: 
        - integration/sage100/index.md
        - SDK Provider: integration/sage100/sdk-provider.md
        - Integration Jobs: integration/sage100/integration-jobs.md
      - Sage Intacct: 
        - integration/intacct/index.md
        - SDK Provider: integration/intacct/sdk-provider.md
        - Integration Jobs: integration/intacct/integration-jobs.md
    - Scheduler: scheduler/manual.md
    - SQLCLR: 
      - sqlclr/index.md
      - Getting Started: sqlclr/getting-started.md
      - Version 6 Upgrade Guide: sqlclr/version-6-upgrade-guide.md
      - CLR Procedure Reference: sqlclr/reference.md
    - Web Desktop: 
         - webdesktop/index.md
         - Data Grid: webdesktop/datagrid/datagrid.md
         - Data Capture: webdesktop/datacapture/data-capture.md
    - Scanner Application: android-application/manual.md
    - Application Security: 
        - security/index.md
        - System Security: security/system-security.md
        - Permissions: security/user-permissions.md
    - Customization:
        - customization/index.md
  - Tools:
    - tools/index.md
    - Jam.dev: tools/jam.md
    - Jaeger: tools/jaeger.md
  - Updates:
    - What's New:
      - V5: updates/V5/whats-new.md
      - V6: 
        - Whats New : updates/V6/whats-new.md
        - CheatSheet : updates/V6/cheatsheet.md
    - Release Notes: updates/release-notes.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html